FAMILIAS = {
    "EXPOSICIÓN A, O CONTACTO CON RADIACIONES": "Atmósfera y sustancias peligrosas",
    "INTOXICACION-ASFIXIA-ABSORCION-RADIACIONES": "Atmósfera y sustancias peligrosas",
    "CAÍDAS DE PERSONAS": "Caída de personas",
    "CAÍDAS DE PERSONAS CON DESNIVELACIÓN [CAÍDAS DESDE ALTURAS (ÁRBOLES, EDIFICIOS, ANDAMIOS, ESCALERAS, MÁQUINAS DE TRABAJO": "Caída de personas",
    "CAÍDAS DE PERSONAS QUE OCURREN AL MISMO NIVEL": "Caída de personas",
    "ATRAPADO EN CHUTES O TOLVAS Y OTROS DURANTE DESATORO": "Desprendimiento de rocas y mineral",
    "ATRAPADO POR DERRUMBE, DESLIZAMIENTO, SOPLADO DE MINERAL O DESMONTE": "Desprendimiento de rocas y mineral",
    "ATRAPADO POR SUCCIÓN DE MINERAL / DESMONTE": "Desprendimiento de rocas y mineral",
    "DERRUMBE (CAÍDAS DE MASAS DE TIERRA, DE ROCAS, DE PIEDRAS, DE NIEVE)": "Desprendimiento de rocas y mineral",
    "DESPRENDIMIENTO DE ROCAS": "Desprendimiento de rocas y mineral",
    "OTROS - ESTALLIDO DE ROCAS": "Desprendimiento de rocas y mineral",
    "EXPOSICIÓN A, O CONTACTO CON ENERGÍA ELÉCTRICA": "Energía eléctrica",
    "EXPOSICIÓN A, O CONTACTO CON, LA CORRIENTE ELÉCTRICA": "Energía eléctrica",
    "ESFUERZOS FÍSICOS EXCESIVOS AL EMPUJAR OBJETOS O TIRAR DE ELLOS": "Esfuerzos físicos",
    "ESFUERZOS FÍSICOS EXCESIVOS AL LEVANTAR OBJETOS": "Esfuerzos físicos",
    "GOLPES POR OBJETOS EN DETONACIÓN DE EXPLOSIVOS": "Explosivos",
    "OTROS TIPOS - AHOGAMIENTO POR INUNDACION": "Fenómenos naturales",
    "OTROS TIPOS - DESCARGA ELECTRICA POR RAYO": "Fenómenos naturales",
    "OTROS TIPOS - HUAYCO": "Fenómenos naturales",
    "ATRAPADA ENTRE DOS OBJETOS MÓVILES (A EXCEPCIÓN DE LOS OBJETOS VOLANTES O QUE CAEN)": "Maquinaria y atrapamiento",
    "ATRAPADA ENTRE UN OBJETO INMÓVIL Y UN OBJETO MÓVIL": "Maquinaria y atrapamiento",
    "ATRAPADA POR UN OBJETO": "Maquinaria y atrapamiento",
    "CHOQUES CONTRA O ATRAPADO EN O GOLPES POR OPERACIÓN DE MAQUINARIA": "Maquinaria y atrapamiento",
    "OTRO TIPOS - CAMPANEO": "Maquinaria y atrapamiento",
    "OTROS TIPOS - IZAJE DE EQUIPOS": "Maquinaria y atrapamiento",
    "CAÍDAS DE OBJETOS EN CURSO DE MANUTENCIÓN MANUAL": "Objetos y materiales",
    "CHOQUE CONTRA OBJETOS MÓVILES": "Objetos y materiales",
    "CHOQUES CONTRA O GOLPES POR OBJETOS DURANTE EL CARGUÍO Y DESCARGA DE MINERAL/DESMONTE": "Objetos y materiales",
    "CHOQUES CONTRA O GOLPES POR OBJETOS DURANTE EL MANIPULEO DE MATERIALES": "Objetos y materiales",
    "CHOQUES CONTRA OBJETOS INMÓVILES (A EXCEPCIÓN DE CHOQUES DEBIDOS A UNA CAÍDA ANTERIOR)": "Objetos y materiales",
    "DESPLOME (DE EDIFICIOS, DE MUROS, DE ANDAMIOS, DE ESCALERAS, DE PILAS DE MERCANCÍAS)": "Objetos y materiales",
    "GOLPES POR HERRAMIENTAS": "Objetos y materiales",
    "GOLPES POR OBJETOS MÓVILES (COMPRENDIDOS LOS FRAGMENTOS VOLANTES Y LAS PARTÍCULAS), A EXCEPCIÓN DE LOS GOLPES POR OBJETO": "Objetos y materiales",
    "OTRAS CAÍDAS DE OBJETOS": "Objetos y materiales",
    "PISADAS SOBRE OBJETOS": "Objetos y materiales",
    "OTROS": "Otros",
    "OTROS TIPOS - CAUSA NATURAL": "Otros",
    "ACARREO Y TRANSPORTE": "Tránsito y transporte",
    "CHOQUES CONTRA O ATRAPADO EN O GOLPES POR VEHÍCULO MOTORIZADO (TRÁNSITO)": "Tránsito y transporte",
}